package com.event.serviceImpl;

import com.event.entity.Event;
import com.event.entity.User;
import com.event.service.CertificateService;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.draw.LineSeparator;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class CertificateServiceImpl implements CertificateService {

    @Override
    public ByteArrayInputStream generateCertificate(User user, Event event) {
        Document document = new Document(PageSize.A4.rotate());
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Font Definitions
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 36, Color.DARK_GRAY);
            Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA, 18, Color.GRAY);
            Font nameFont = FontFactory.getFont(FontFactory.TIMES_BOLDITALIC, 28, new Color(99, 102, 241)); // Primary color
            Font textFont = FontFactory.getFont(FontFactory.HELVETICA, 14, Color.BLACK);
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.LIGHT_GRAY);

            // Add Border-like spacing
            document.add(new Paragraph("\n"));

            // Header
            Paragraph title = new Paragraph("CERTIFICATE OF PARTICIPATION", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("\n"));

            Paragraph subtitle = new Paragraph("This is to certify that", subTitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            document.add(subtitle);

            document.add(new Paragraph("\n"));

            // Name
            Paragraph name = new Paragraph(user.getFirstName() + " " + user.getLastName(), nameFont);
            name.setAlignment(Element.ALIGN_CENTER);
            document.add(name);

            document.add(new Paragraph("\n"));

            // Content
            String contentStr = String.format("has successfully participated in the event\n\"%s\"\nconducted on %s.", 
                    event.getTitle(), 
                    event.getDate().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
            Paragraph content = new Paragraph(contentStr, textFont);
            content.setAlignment(Element.ALIGN_CENTER);
            content.setLeading(20f);
            document.add(content);

            document.add(new Paragraph("\n\n\n"));

            // Signatures Placeholder
            Paragraph signatures = new Paragraph("__________________________          __________________________", textFont);
            signatures.setAlignment(Element.ALIGN_CENTER);
            document.add(signatures);

            Paragraph sigLabels = new Paragraph("Event Organizer                     EventPulse Platform", subTitleFont);
            sigLabels.setAlignment(Element.ALIGN_CENTER);
            document.add(sigLabels);

            // Footer
            document.add(new Paragraph("\n\n"));
            LineSeparator ls = new LineSeparator();
            ls.setLineColor(new Color(230, 230, 230));
            document.add(ls);
            
            Paragraph footer = new Paragraph("Generated by EventPulse | Verified Certificate ID: EP-" + System.currentTimeMillis(), footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}
