import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, X, QrCode, ClipboardCheck, MessageSquare } from "lucide-react";

const QRModal = ({ eventId, eventTitle, qrCodeBase64, onClose }) => {
  const [activeTab, setActiveTab] = useState("checkin"); // 'checkin' or 'feedback'
  
  const feedbackUrl = `${window.location.origin}/feedback/submit/${eventId}`;
  const feedbackQrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(feedbackUrl)}`;
  
  // The check-in QR is the one generated by the backend (Base64)
  const checkInQrUrl = qrCodeBase64;

  const currentQr = activeTab === "checkin" ? checkInQrUrl : feedbackQrUrl;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className="card max-w-sm w-full bg-slate-900 border-white/10 relative overflow-hidden"
      >
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-500 hover:text-white z-10"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="text-center mb-6 pt-4">
          <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mx-auto mb-4">
            <QrCode className="text-primary w-6 h-6" />
          </div>
          <h2 className="text-xl font-bold">Event QR Codes</h2>
          <p className="text-slate-400 text-sm mt-1">{eventTitle}</p>
        </div>

        {/* Tab Switcher */}
        <div className="flex bg-slate-800/50 p-1 rounded-xl mb-6 mx-4">
          <button
            onClick={() => setActiveTab("checkin")}
            className={`flex-1 flex items-center justify-center gap-2 py-2 text-xs font-semibold rounded-lg transition-all ${
              activeTab === "checkin" ? "bg-primary text-white shadow-lg" : "text-slate-400 hover:text-white"
            }`}
          >
            <ClipboardCheck className="w-3.5 h-3.5" /> Check-In
          </button>
          <button
            onClick={() => setActiveTab("feedback")}
            className={`flex-1 flex items-center justify-center gap-2 py-2 text-xs font-semibold rounded-lg transition-all ${
              activeTab === "feedback" ? "bg-primary text-white shadow-lg" : "text-slate-400 hover:text-white"
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5" /> Feedback
          </button>
        </div>

        <div className="bg-white p-4 rounded-2xl mb-6 mx-4 flex justify-center shadow-inner">
          <img src={currentQr} alt="Event QR Code" className="w-48 h-48" />
        </div>

        <div className="space-y-3 px-4 pb-4">
          <p className="text-[10px] text-slate-500 text-center leading-relaxed">
            {activeTab === "checkin" 
              ? "Attendees scan this to mark their attendance for this event instantly."
              : "Scan to instantly access the feedback form for this event."}
          </p>
          <a 
            href={currentQr} 
            download={`${eventTitle}_${activeTab}_QR.png`}
            className="btn-primary w-full py-2.5 text-sm flex items-center justify-center gap-2"
            target="_blank"
            rel="noreferrer"
          >
            <Download className="w-4 h-4" /> Download QR
          </a>
        </div>
      </motion.div>
    </motion.div>
  );
};

export default QRModal;
