spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

razorpay.key.id=YOUR_KEY_ID
razorpay.key.secret=YOUR_SECRET_KEY

sendgrid.api.key=YOUR_SENDGRID_KEY
